import {createIconSetFromIcoMoon} from 'react-native-vector-icons';
import icoMoonConfig from './selection.json';
/*
interface IconProps {
    name: Icon;
    size: number;
    color: string;
    style: any;
}*/

export const DakIcon = createIconSetFromIcoMoon(icoMoonConfig);

export enum Icon {
    EYE = 'eye',
    EYE_OFF = 'eye-off',
    FACE_ID = 'FaceID',
    TOUCH_ID = 'TouchID',
    ZOOM_IN = 'Zoom-in',
    ZOOM_OUT = 'Zoom-out',
    FOLDER = 'Folder',
    NEW_MESSAGE = 'New-message',
    NEW_MESSAGE_2 = 'New-message-2',
    MESSAGE = 'Message',
    TRASH = 'Trash',
    CHECKMARK = 'Checkmark',
    CALENDAR = 'Calendar',
    LOCK = 'Lock',
    CHEVRON_LEFT = 'Chevron-left',
    ARROW_DOWN = 'Arrow-down',
    PARAGRAPH = 'Paragraph',
    SETTINGS = 'Settings',
    CHEVRON_DOWN = 'Chevron-down',
    ATTACHMENT = 'Attachment',
    LOCATION = 'Location',
    INFO = 'Info',
    SELF_SERVICE = 'Self-service',
    EDIT = 'Edit',
    CHEVRON_UP = 'Chevron-up',
    DOWNLOAD_ALL = 'Download-all',
    MOVE_FOLDER = 'Move-folder',
    FORWARD_MESSAGE = 'Forward-message',
    UNREAD = 'Unread',
    PLUS = 'Plus',
    PROFILE = 'Profile',
    PROFILE_ROUND = 'Profile-round',
    TIME = 'Time',
    SIGNATURE = 'Signature',
    CHEVRON_RIGHT = 'Chevron-right',
    DRAFT = 'Draft',
    LANGUAGE = 'Language',
    SUPPORT = 'Support',
    PRINT = 'Print',
    LINK = 'Link',
    CHANGE_USER = 'Change-user',
    REPLY_ARROW = 'Reply-arrow',
    TUTORIAL = 'Tutorial',
    MINUS = 'Minus',
    LIST = 'List',
    DOWNLOAD = 'Download',
    REPLY = 'Reply',
    CHAT = 'Chat',
    CLOSE = 'Close',
    FLAG = 'Flag',
    FILTER = 'Filter',
    PAYMENT = 'Payment',
    CONSENT = 'Consent',
    DATA = 'Data',
    SEARCH = 'Search',
    SEARCH_2 = 'Search-2',
    NOTIFICATION = 'Notification',
    ACTIVITY = 'Activity',
    NOTE = 'Note',
    EXTERNAL_LINK = 'External-link',
    SEND = 'Send',
    FORWARD_ARROW = 'Forward-arrow',
    FEEDBACK = 'Feedback',
    CONFIRMATION = 'Confirmation',
    MEATBALLS = 'Meatballs',
    WARNING = 'Warning',
    MEATBALLS_VERTICAL = 'Meatballs-vertical',
    ARROW_UP = 'Arrow-up',
    PREPARATION = 'Preparation',
    REGISTRATION = 'Registration',
    HAMBURGER = 'Hamburger',
    NEW_MAIL = 'New-mail',
    NEW_MAIL_2 = 'New-mail-2',
    ALL_MAIL = 'All-mail',
    ALL_MAIL_2 = 'All-mail-2',
    FACEID = 'FaceID',
    TOUCHID = 'TouchID',
    BOLD = 'B',
    ITALIC = 'I',
    STRIKE = 'Strike',
    UNDERLINE = 'Frame-2261',
    BULLET_LIST = 'format_list_bulleted',
    ORDERED_LIST = 'format_list_numbered',
}
